baseURL = "https://www.chrismahoney.com.au"
DefaultContentLanguage = "en"
languageCode = "en-au"
title = "Personal Website"
theme = "beautifulhugo"
metaDataFormat = "yaml"
enableEmoji = true
googleAnalytics = ""

[Params]
    homeTitle = "Chris Mahoney"
    subtitle = "I try to understand things clearly and explain them well"
    dateFormat = "02 Jan 2006"
    date = "2021-01-10"
    mainSections = ["post","posts"]
    mainPages = ["About", "Corporate", "Academia", "Projects", "Blogs", "Apps"]
    logo = "images/ChrisMahoneyCorporate.jpg"
    #logo = "images/ChrisMahoneyInspirational_Modified2.jpg"
    commit = true
    comments = true
    readingTime = true
    wordCount = true
    showRelatedPosts = true
    hideAuthor = true

[Author]
    name = "Chris Mahoney"
    website = "chrismahoney.com.au"
    email = "chrismahoney@hotmail.com"
    linkedin = "chrimaho"
    medium = "chrimaho"
    github = "chrimaho"
    stackoverflow = "users/12036005/chrimaho"

[menu]

    [[menu.main]]
        identifier = "about"
        name = "About Me"
        weight = 1

        [[menu.main]]
            parent = "about"
            name = "About"
            url = "/page/about/"
            weight = 1

        [[menu.main]]
            parent = "about"
            name = "Corporate"
            url = "/page/corporate/"
            weight = 2

        [[menu.main]]
            parent = "about"
            name = "Academia"
            url = "/page/academia/"
            weight = 3

    [[menu.main]]
        identifier = "stuff"
        name = "My Stuff"
        weight = 2

        [[menu.main]]
            parent = "stuff"
            name = "Blogs"
            url = "/blogs/"
            weight = 5

        [[menu.main]]
            parent = "stuff"
            name = "Apps"
            url = "/apps/"
            weight = 6

        [[menu.main]]
            parent = "stuff"
            name = "Projects"
            url = "/projects/"
            weight = 4

    [[menu.main]]
        name = "Resume"
        url = "/page/resume/"
        weight = 7
