# Base configs
baseURL = "https://www.chrismahoney.com.au"
DefaultContentLanguage = "en"
languageCode = "en-au"
title = "Personal Website"
theme = "beautifulhugo"
metaDataFormat = "yaml"
enableEmoji = true
googleAnalytics = "UA-106819690-1"

# Site params
[Params]
    homeTitle = "Chris Mahoney"
    subtitle = "I try to understand things clearly and explain them well"
    dateFormat = "02 Jan 2006"
    date = "2021-01-10"
    mainSections = ["post","posts"]
    mainPages = ["About", "Corporate", "Academia", "Projects", "Blogs", "Apps"]
    logo = "images/ChrisMahoneyCorporate.jpg"
    #logo = "images/ChrisMahoneyInspirational_Modified2.jpg"
    favicon = "images/CM_Icon.png"
    enableGitInfo = true
    commit = "https://github.com/chrimaho/chrismahoney/tree/"
    comments = true
    readingTime = true
    wordCount = true
    showRelatedPosts = true
    hideAuthor = true
    includePageLastModified = false
    includePostLastModified = false

# Author deets
[Author]
    name = "Chris Mahoney"
    website = "chrismahoney.com.au"
    email = "chrismahoney@hotmail.com"
    linkedin = "chrimaho"
    medium = "chrimaho"
    github = "chrimaho"
    stackoverflow = "users/12036005/chrimaho"

# Site menu's
[menu]

    [[menu.main]]
        identifier = "about"
        name = "About Me"
        weight = 0.1

        [[menu.main]]
            parent = "about"
            name = "About"
            url = "/page/about/"
            weight = 1

        [[menu.main]]
            parent = "about"
            name = "Professional"
            url = "/page/professional/"
            weight = 2

        [[menu.main]]
            parent = "about"
            name = "Education"
            url = "/page/education/"
            weight = 3

    [[menu.main]]
        identifier = "stuff"
        name = "My Stuff"
        weight = 0.2

        [[menu.main]]
            parent = "stuff"
            name = "Blogs"
            url = "/blogs/"
            weight = 1

        [[menu.main]]
            parent = "stuff"
            name = "Apps"
            url = "/apps/"
            weight = 2

        [[menu.main]]
            parent = "stuff"
            name = "Projects"
            url = "/projects/"
            weight = 3

    [[menu.main]]
        name = "Résumé"
        url = "/page/resume/"
        weight = 0.3

# Turn on the ability to render raw html
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true