baseURL = "http://www.chrismahoney.com.au/"
DefaultContentLanguage = "en"
languageCode = "en-au"
title = "Chris Mahoney"
theme = "beautifulhugo"
metaDataFormat = "yaml"

[Params]
    homeTitle = "Chris Mahoney"
    subtitle = "Homepage for ChrisMahoney.com.au"
    dateFormat = "02 Jan 2006"
    commit = true
    comments = true
    readingTime = true
    wordCount = true
    showRelatedPosts = true
    hideAuthor = true

[Author]
    name = "Chris Mahoney"
    website = "chrismahoney.com.au"
    email = "chrismahoney@hotmail.com"
    github = "chrimaho"
    linkedin = "chrimaho"
    kaggle = "chrimaho"
    stackoverflow = "users/12036005/chrimaho"
    medium = "chrimaho"

[menu]

    [[menu.main]]
        name = "About"
        url = "/pages/about/"
        weight = 1

    [[menu.main]]
        name = "Corporate"
        url = "/pages/corporate/"
        weight = 2

    [[menu.main]]
        name = "Academia"
        url = "/pages/academia/"
        weight = 3

    [[menu.main]]
        name = "Projects"
        url = "/pages/projects/"
        weight = 4

    [[menu.main]]
        name = "Blogs"
        url = "/pages/blogs/"
        weight = 5

    [[menu.main]]
        name = "Apps"
        url = "/pages/apps/"
        weight = 6

    [[menu.main]]
        name = "Resume"
        url = "/pages/resume/"
        weight = 7


[[social_icons]]
    id = "medium"
    url = "https://medium.com/@%s"
    title = "Medium"
    icon = "fab fa-medium"